export const tools = [
  // ── Chat AI ─────────────────────────────────────────────────────────────
  {
    id: "claude-ai",
    name: "Claude",
    tagline: "Anthropic's thoughtful AI assistant for reasoning, coding, and analysis.",
    category: "Chat AI",
    tags: ["chat", "llm", "coding", "writing"],
    status: "live",
    url: "https://claude.ai",
    pricing: "free",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "OpenAI's flagship conversational AI — the tool that started the era.",
    category: "Chat AI",
    tags: ["chat", "llm", "assistant", "gpt"],
    status: "live",
    url: "https://chat.openai.com",
    pricing: "$20/mo",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    tagline: "AI-powered search engine with real-time answers and citations.",
    category: "Chat AI",
    tags: ["search", "research", "citations", "real-time"],
    status: "live",
    url: "https://perplexity.ai",
    pricing: "free",
  },
  {
    id: "monica",
    name: "Monica",
    tagline: "All-in-one AI assistant for browsing, writing, and translation.",
    category: "Chat AI",
    tags: ["assistant", "browser", "writing", "translation"],
    status: "live",
    url: "https://monica.im",
    pricing: "$10/mo",
    referralUrl: "https://monica.im/invitation?c=JUFU7NXN",
    badgeLabel: "invite",
    featured: true,
  },
  {
    id: "droxy",
    name: "Droxy",
    tagline: "Build and deploy AI chatbots trained on your own content.",
    category: "Chat AI",
    tags: ["chatbot", "custom", "deployment", "no-code"],
    status: "live",
    url: "https://droxy.ai",
    pricing: "paid",
    referralUrl: "https://app.droxy.ai/sign-up?via=dan",
    featured: true,
  },
  {
    id: "dante-ai",
    name: "Dante AI",
    tagline: "Create custom GPT chatbots from your documents and websites.",
    category: "Chat AI",
    tags: ["chatbot", "custom-gpt", "documents", "no-code"],
    status: "live",
    url: "https://dante-ai.com",
    pricing: "paid",
  },
  {
    id: "writesonic",
    name: "Writesonic",
    tagline: "Updated Chat Bot, Create and Optimize SEO",
    category: "Chat AI",
    tags: ["seo", "chat", "content", "copywriting"],
    status: "live",
    url: "https://writesonic.com",
    pricing: "free trial",
    referralUrl: "https://writesonic.com?fp_ref=3dz",
  },
  {
    id: "flowgpt",
    name: "FlowGPT",
    tagline: "Community-driven prompt library and AI chat platform.",
    category: "Chat AI",
    tags: ["prompts", "community", "chat", "ai-tools"],
    status: "live",
    url: "https://flowgpt.com",
    pricing: "free",
  },

  // ── Creative ────────────────────────────────────────────────────────────
  {
    id: "canva",
    name: "Canva",
    tagline: "AI-powered design platform for graphics, presentations, and more.",
    category: "Creative",
    tags: ["design", "graphics", "templates", "magic-ai"],
    status: "live",
    url: "https://canva.com",
    pricing: "free",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    tagline: "Premium text-to-image AI with cinematic, painterly output.",
    category: "Creative",
    tags: ["image-gen", "text-to-image", "art", "design"],
    status: "live",
    url: "https://midjourney.com",
    pricing: "paid",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    tagline: "AI image generation with accurate text rendering inside images.",
    category: "Creative",
    tags: ["image-gen", "text-rendering", "logos", "typography"],
    status: "live",
    url: "https://ideogram.ai",
    pricing: "free",
  },
  {
    id: "playground-ai",
    name: "Playground AI",
    tagline: "Create and remix AI images with a generous free daily allowance.",
    category: "Creative",
    tags: ["image-gen", "remixing", "stable-diffusion", "free"],
    status: "live",
    url: "https://playgroundai.com",
    pricing: "free",
  },
  {
    id: "bing-create",
    name: "Bing Create",
    tagline: "Microsoft's free DALL-E powered image generator in the browser.",
    category: "Creative",
    tags: ["image-gen", "dall-e", "microsoft", "free"],
    status: "live",
    url: "https://bing.com/create",
    pricing: "free",
  },
  {
    id: "krea",
    name: "Krea",
    tagline: "Real-time AI image generation and enhancement with live canvas.",
    category: "Creative",
    tags: ["image-gen", "real-time", "upscaling", "canvas"],
    status: "live",
    url: "https://krea.ai",
    pricing: "free",
  },
  {
    id: "upscayl",
    name: "Upscayl",
    tagline: "Free and open-source AI image upscaler for desktop.",
    category: "Creative",
    tags: ["upscaling", "open-source", "desktop", "image"],
    status: "live",
    url: "https://upscayl.org",
    pricing: "free",
  },
  {
    id: "topaz-labs",
    name: "Topaz Labs",
    tagline: "Professional AI photo and video enhancement and noise reduction.",
    category: "Creative",
    tags: ["photo", "enhancement", "noise-reduction", "upscaling"],
    status: "live",
    url: "https://topazlabs.com",
    pricing: "paid",
  },
  {
    id: "replicate",
    name: "Replicate",
    tagline: "Run any open-source AI model via a clean API with pay-per-use pricing.",
    category: "Creative",
    tags: ["api", "open-source", "models", "stable-diffusion"],
    status: "live",
    url: "https://replicate.com",
    pricing: "free",
  },
  {
    id: "stability-ai",
    name: "Stability AI",
    tagline: "Stable Diffusion - Image, Video, Audio, 3D, Language",
    category: "Creative",
    tags: ["image-gen", "stable-diffusion", "video", "audio", "3d"],
    status: "live",
    url: "https://stability.ai",
    pricing: "free trial",
    badgeLabel: "3-day trial",
  },
  {
    id: "imglarger",
    name: "IMGLarger",
    tagline: "Best Image Enlarger, Enhancer",
    category: "Creative",
    tags: ["upscaling", "enhancer", "free", "image"],
    status: "live",
    url: "https://imglarger.com",
    pricing: "free",
  },
  {
    id: "tinywow",
    name: "TinyWow",
    tagline: "Best Free Image Tools",
    category: "Creative",
    tags: ["image-tools", "free", "online", "editing"],
    status: "live",
    url: "https://tinywow.com",
    pricing: "free limited",
  },
  {
    id: "upscale-media",
    name: "Upscale Media",
    tagline: "Free Ai Upscaler",
    category: "Creative",
    tags: ["upscaling", "enhancer", "free", "online"],
    status: "live",
    url: "https://upscale.media",
    pricing: "free",
  },
  {
    id: "pixabay",
    name: "Pixabay",
    tagline: "Massive library of free stock photos, illustrations, and videos.",
    category: "Creative",
    tags: ["stock-photos", "free", "illustrations", "videos"],
    status: "live",
    url: "https://pixabay.com",
    pricing: "free",
  },
  {
    id: "unsplash",
    name: "Unsplash",
    tagline: "Beautiful, royalty-free high-resolution photography for any project.",
    category: "Creative",
    tags: ["stock-photos", "royalty-free", "photography", "high-res"],
    status: "live",
    url: "https://unsplash.com",
    pricing: "free",
  },
  {
    id: "remove-bg",
    name: "Remove.bg",
    tagline: "Instantly remove image backgrounds with one click using AI.",
    category: "Creative",
    tags: ["background-removal", "photo-editing", "cutout", "fast"],
    status: "live",
    url: "https://remove.bg",
    pricing: "free",
  },
  {
    id: "rasterbator",
    name: "Rasterbator",
    tagline: "Create giant multi-page poster prints from any image online.",
    category: "Creative",
    tags: ["poster", "print", "large-format", "design"],
    status: "live",
    url: "https://rasterbator.net",
    pricing: "free",
  },
  {
    id: "rawpixel",
    name: "Rawpixel",
    tagline: "Free design resources — stock images, vectors, mockups and illustrations.",
    category: "Creative",
    tags: ["mockup", "design", "stock", "free"],
    status: "live",
    url: "https://rawpixel.com",
    pricing: "free",
  },
  {
    id: "pngtree",
    name: "PNGTree",
    tagline: "Millions of free PNG images, backgrounds, and design templates.",
    category: "Creative",
    tags: ["png", "backgrounds", "templates", "design"],
    status: "live",
    url: "https://pngtree.com",
    pricing: "free",
    referralUrl: "https://pngtree.com/?sce=af&id=28851",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    tagline: "Marketing, sales and CRM platform — AI-powered product pics and social media content.",
    category: "Creative",
    tags: ["branding", "content", "marketing", "ai"],
    status: "live",
    url: "https://hubspot.com",
    pricing: "paid",
  },
  {
    id: "clipdrop",
    name: "Clipdrop",
    tagline: "AI photo editing tools including cleanup, relight, and background swap.",
    category: "Creative",
    tags: ["photo-editing", "cleanup", "relight", "background"],
    status: "live",
    url: "https://clipdrop.co",
    pricing: "free",
  },
  {
    id: "civitai",
    name: "Civitai",
    tagline: "Free AI image prompts and LoRA models — community styles and generators.",
    category: "Creative",
    tags: ["prompts", "lora", "models", "image", "styles"],
    status: "live",
    url: "https://civitai.com",
    pricing: "free",
  },
  {
    id: "ezgif",
    name: "EZGif",
    tagline: "Create and edit free animated GIFs online — simple and fast.",
    category: "Creative",
    tags: ["gif", "animation", "free", "editor"],
    status: "live",
    url: "https://ezgif.com",
    pricing: "free",
  },
  {
    id: "stockimg-qr",
    name: "Stockimg QR",
    tagline: "AI QR Code Generator — style and customize free QR codes instantly.",
    category: "Creative",
    tags: ["qr-code", "ai", "branding", "marketing"],
    status: "live",
    url: "https://stockimg.ai/category/ai-qr-code-generator",
    pricing: "free",
  },
  {
    id: "artguru",
    name: "ArtGuru",
    tagline: "AI art generator with multiple styles including anime and portraits.",
    category: "Creative",
    tags: ["image-gen", "anime", "portraits", "art-styles"],
    status: "live",
    url: "https://artguru.ai",
    pricing: "free",
  },
  {
    id: "rosebud",
    name: "Rosebud",
    tagline: "AI-powered game creation platform for making games from a prompt.",
    category: "Creative",
    tags: ["game-creation", "ai", "no-code", "games"],
    status: "live",
    url: "https://rosebud.ai",
    pricing: "free",
  },
  {
    id: "pixverse",
    name: "Pixverse",
    tagline: "Text to Video, Image to Video, Upscale",
    category: "Creative",
    tags: ["video-gen", "image-to-video", "animation", "ai"],
    status: "live",
    url: "https://pixverse.ai",
    pricing: "free",
  },
  {
    id: "snackprompt",
    name: "Snackprompt",
    tagline: "Sell and discover pre-made prompts for ChatGPT, Midjourney, and more.",
    category: "Creative",
    tags: ["prompts", "chatgpt", "midjourney", "marketplace"],
    status: "live",
    url: "https://snackprompt.com",
    pricing: "free",
  },
  {
    id: "mockuuups",
    name: "Mockuuups Studio",
    tagline: "Free mock ups for websites and apps — high quality design assets.",
    category: "Creative",
    tags: ["mockup", "design", "assets", "website"],
    status: "live",
    url: "https://mockuuups.studio",
    referralUrl: "https://mockuuups.studio/?via=dan",
    pricing: "free",
  },
  {
    id: "psdrepo",
    name: "PSDrepo",
    tagline: "Free mock ups for websites — design resources and PSD files.",
    category: "Creative",
    tags: ["mockup", "design", "psd", "free"],
    status: "live",
    url: "https://psdrepo.com",
    pricing: "free",
  },
  {
    id: "unblast",
    name: "Unblast",
    tagline: "Free mock ups and design resources — fonts, templates and graphics.",
    category: "Creative",
    tags: ["mockup", "design", "resources", "free"],
    status: "live",
    url: "https://unblast.com",
    pricing: "free",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Text to AI voice generator — record, clone and create realistic voices.",
    category: "Creative",
    tags: ["voice", "text-to-speech", "cloning", "ai", "audio"],
    status: "live",
    url: "https://elevenlabs.io",
    referralUrl: "https://try.elevenlabs.io/3dzlabs",
    pricing: "free limited",
  },
  {
    id: "suno-creative",
    name: "Suno",
    tagline: "Text to Song, /Sing, /chirp",
    category: "Creative",
    tags: ["music-gen", "text-to-song", "ai", "audio"],
    status: "live",
    url: "https://suno.ai",
    pricing: "free",
    referralUrl: "https://suno.com/invite/@3dzlabs",
  },
  {
    id: "uvr",
    name: "Ultimate Vocal Remover",
    tagline: "Isolates Music, Vocals, Instruments, free",
    category: "Creative",
    tags: ["vocal-removal", "stems", "audio", "free"],
    status: "live",
    url: "https://ultimatevocalremover.com",
    pricing: "free",
  },
  {
    id: "lalal-creative",
    name: "Lalal.ai",
    tagline: "Isolates Music, Vocals, Instruments, free limited",
    category: "Creative",
    tags: ["vocal-removal", "stems", "audio", "stem-splitting"],
    status: "live",
    url: "https://lalal.ai",
    pricing: "free limited",
  },
  {
    id: "wav2lip",
    name: "Wav2Lip",
    tagline: "Lip Sync Videos",
    category: "Creative",
    tags: ["lip-sync", "video", "audio", "ai"],
    status: "live",
    url: "https://wav2lip.org",
    pricing: "free",
  },
  {
    id: "storyblocks-creative",
    name: "Storyblocks",
    tagline: "Royalty Free Stock Videos",
    category: "Creative",
    tags: ["stock-video", "royalty-free", "footage", "assets"],
    status: "live",
    url: "https://storyblocks.com",
    pricing: "paid",
  },
  {
    id: "genmo-creative",
    name: "Genmo",
    tagline: "Text to 3D Models, Images, Video - Real World Models",
    category: "Creative",
    tags: ["3d-models", "text-to-3d", "image-gen", "video-gen"],
    status: "live",
    url: "https://genmo.ai",
    pricing: "free",
  },
  {
    id: "pixop-creative",
    name: "Pixop",
    tagline: "High Quality Video Upscaler",
    category: "Creative",
    tags: ["upscaling", "video", "enhancement", "professional"],
    status: "live",
    url: "https://pixop.com",
    pricing: "paid",
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    tagline: "AI image and generative fill design tools by Adobe.",
    category: "Creative",
    tags: ["image-gen", "generative-fill", "adobe", "design"],
    status: "live",
    url: "https://firefly.adobe.com",
    pricing: "free",
  },

  // ── Video ───────────────────────────────────────────────────────────────
  {
    id: "invideo-ai",
    name: "Invideo AI",
    tagline: "Turn a text prompt or script into a polished video in minutes.",
    category: "Video",
    tags: ["text-to-video", "marketing", "social", "voiceover"],
    status: "live",
    url: "https://invideo.io",
    pricing: "$20/mo",
    referralUrl: "https://invideo.io/i/3dz-ws",
    featured: true,
  },
  {
    id: "kaiber",
    name: "Kaiber",
    tagline: "Transform audio, images, and prompts into cinematic AI video.",
    category: "Video",
    tags: ["ai-video", "animation", "music-video", "cinematic"],
    status: "live",
    url: "https://kaiber.ai",
    pricing: "paid",
  },
  {
    id: "visla",
    name: "Visla",
    tagline: "AI video creation platform for marketing and business content.",
    category: "Video",
    tags: ["video-creation", "marketing", "business", "stock"],
    status: "live",
    url: "https://visla.us",
    pricing: "free",
    referralUrl: "https://visla.us/r/PN2EHM",
    featured: true,
  },
  {
    id: "capcut",
    name: "CapCut",
    tagline: "Free AI-powered video editor with auto-captions and effects.",
    category: "Video",
    tags: ["video-editor", "captions", "effects", "mobile"],
    status: "live",
    url: "https://capcut.com",
    pricing: "free",
  },
  {
    id: "heygen",
    name: "HeyGen",
    tagline: "Create AI avatar videos with voice cloning and translation.",
    category: "Video",
    tags: ["ai-avatar", "voice-cloning", "translation", "presenter"],
    status: "live",
    url: "https://heygen.com",
    pricing: "paid",
  },
  {
    id: "d-id",
    name: "D-ID",
    tagline: "Animate still photos and generate talking AI presenters.",
    category: "Video",
    tags: ["talking-avatar", "photo-animation", "presenter", "digital-human"],
    status: "live",
    url: "https://d-id.com",
    pricing: "paid",
  },
  {
    id: "pika",
    name: "Pika",
    tagline: "Generate and edit video from text, images, or existing clips.",
    category: "Video",
    tags: ["text-to-video", "image-to-video", "editing", "generation"],
    status: "live",
    url: "https://pika.art",
    pricing: "free",
  },
  {
    id: "wisecut",
    name: "Wisecut",
    tagline: "Auto cut and edit videos with AI — FREE limited plan available.",
    category: "Video",
    tags: ["video-editing", "auto-cut", "reels", "ai"],
    status: "live",
    url: "https://app.wisecut.ai",
    pricing: "free limited",
  },
  {
    id: "2short-ai",
    name: "2short.ai",
    tagline: "Repurpose long videos into viral short-form clips automatically.",
    category: "Video",
    tags: ["shorts", "repurposing", "clips", "social-media"],
    status: "live",
    url: "https://2short.ai",
    pricing: "paid",
  },
  {
    id: "pictory",
    name: "Pictory",
    tagline: "Blog to YouTube Video - 10min X 3 are Free",
    category: "Video",
    tags: ["text-to-video", "blog", "youtube", "branded"],
    status: "live",
    url: "https://pictory.ai",
    pricing: "$30/mo",
  },
  {
    id: "oxolo",
    name: "Oxolo",
    tagline: "Turn any product URL into a personalized AI sales video and agent in seconds.",
    category: "Video",
    tags: ["sales", "ai-agent", "product-video", "ecommerce"],
    status: "live",
    url: "https://oxolo.com",
    pricing: "paid",
  },
  {
    id: "genmo",
    name: "Genmo",
    tagline: "AI video and animation generator from text prompts and images.",
    category: "Video",
    tags: ["ai-video", "animation", "text-to-video", "image-to-video"],
    status: "live",
    url: "https://genmo.ai",
    pricing: "free",
  },
  {
    id: "runwayml",
    name: "RunwayML",
    tagline: "Professional AI video generation and editing suite for creators.",
    category: "Video",
    tags: ["ai-video", "gen-2", "editing", "professional"],
    status: "live",
    url: "https://runwayml.com",
    pricing: "paid",
  },
  {
    id: "pixop",
    name: "Pixop",
    tagline: "AI-powered video upscaling and restoration for older footage.",
    category: "Video",
    tags: ["upscaling", "restoration", "video", "enhancement"],
    status: "live",
    url: "https://pixop.com",
    pricing: "paid",
  },
  {
    id: "clipbuddy",
    name: "ClipBuddy",
    tagline: "AI clip finder and repurposing tool for long-form video content.",
    category: "Video",
    tags: ["clips", "repurposing", "youtube", "shorts"],
    status: "live",
    url: "https://clipbuddy.io",
    pricing: "paid",
  },
  {
    id: "vizard",
    name: "Vizard",
    tagline: "Repurpose webinars and long videos into social-ready short clips.",
    category: "Video",
    tags: ["repurposing", "webinar", "clips", "social-media"],
    status: "live",
    url: "https://vizard.ai",
    pricing: "$16/mo",
    referralUrl: "https://vizard.ai/?via=3dz",
  },
  {
    id: "kapwing",
    name: "Kapwing",
    tagline: "Collaborative browser-based video editor with AI subtitles and tools.",
    category: "Video",
    tags: ["video-editor", "subtitles", "collaborative", "browser", "kapwing"],
    status: "live",
    url: "https://kapwing.com",
    pricing: "free",
  },
  {
    id: "kapwing-subtitles",
    name: "Kapwing Subtitles",
    tagline: "Auto-subtitle generator — 99% accurate captions for your videos. Part of Kapwing suite.",
    category: "Video",
    tags: ["subtitles", "captions", "video", "kapwing", "auto"],
    status: "live",
    url: "https://www.kapwing.com/subtitles",
    pricing: "free limited",
  },
  {
    id: "clipchamp",
    name: "Clipchamp",
    tagline: "Microsoft's free browser-based video editor with templates and AI tools.",
    category: "Video",
    tags: ["video-editor", "microsoft", "templates", "browser"],
    status: "live",
    url: "https://clipchamp.com",
    pricing: "free",
  },
  {
    id: "yarn",
    name: "Yarn",
    tagline: "Search and share video clips from movies, TV, and music using quotes.",
    category: "Video",
    tags: ["clips", "movies", "tv", "search"],
    status: "live",
    url: "https://yarn.co",
    pricing: "free",
  },
  {
    id: "intromaker",
    name: "Intro Maker",
    tagline: "Create YouTube video intros for free — use this link for YouTube intros.",
    category: "Video",
    tags: ["intro", "youtube", "video", "free"],
    status: "live",
    url: "https://intromaker.com",
    pricing: "free",
  },
  {
    id: "storyblocks",
    name: "Storyblocks",
    tagline: "Unlimited stock video, audio, and images for creators by subscription.",
    category: "Video",
    tags: ["stock-video", "stock-audio", "subscription", "assets"],
    status: "live",
    url: "https://storyblocks.com",
    pricing: "free",
  },
  {
    id: "plotdot",
    name: "PlotDot",
    tagline: "AI story and script generator for video creators and filmmakers.",
    category: "Video",
    tags: ["script", "story", "filmmaking", "ai-writing"],
    status: "live",
    url: "https://plotdot.ai",
    pricing: "free",
  },
  {
    id: "plazmapunk",
    name: "Plazmapunk",
    tagline: "AI music video generator that syncs visuals to your tracks.",
    category: "Video",
    tags: ["music-video", "ai-video", "sync", "visual"],
    status: "live",
    url: "https://plazmapunk.com",
    pricing: "free",
  },
  {
    id: "filmora",
    name: "Filmora",
    tagline: "AI-powered video editor for creators — Part of the Wondershare suite.",
    category: "Video",
    tags: ["video-editing", "wondershare", "ai", "creative"],
    status: "live",
    url: "https://filmora.wondershare.com",
    pricing: "free limited",
  },
  {
    id: "wondershare",
    name: "Wondershare",
    tagline: "Professional creative suite — video editing, diagramming, media tools and more. Includes Filmora, Virbo, Media.io and Edrawsoft.",
    category: "Video",
    tags: ["suite", "video", "editing", "media", "diagrams", "creative", "wondershare"],
    status: "live",
    url: "https://wondershare.com",
    pricing: "free limited",
  },
  {
    id: "blackmagicdesign",
    name: "DaVinci Resolve",
    tagline: "Best free professional video editor — industry standard color grading and editing.",
    category: "Video",
    tags: ["video-editing", "color", "free", "professional"],
    status: "live",
    url: "https://blackmagicdesign.com",
    pricing: "free",
  },

  // ── Music ───────────────────────────────────────────────────────────────
  {
    id: "suno-ai",
    name: "Suno AI",
    tagline: "Generate complete songs with vocals and instruments from a prompt.",
    category: "Music",
    tags: ["music-gen", "vocals", "songwriting", "audio"],
    status: "live",
    url: "https://suno.ai",
    pricing: "free",
  },
  {
    id: "tracksy",
    name: "Tracksy",
    tagline: "Create royalty-free background music with AI — use code 3DZ for a discount",
    category: "Music",
    tags: ["music", "royalty-free", "background-music", "ai"],
    status: "live",
    url: "https://tracksy.ai",
    referralUrl: "https://tracksy.ai/affiliatecustomers.jsp",
    pricing: "free limited",
  },
  {
    id: "textfx",
    name: "TextFX",
    tagline: "AI-powered text tools for rappers, writers and wordsmiths by Google.",
    category: "Music",
    tags: ["text", "writing", "rap", "lyrics", "google"],
    status: "live",
    url: "https://textfx.withgoogle.com",
    pricing: "free",
  },
  {
    id: "lovo",
    name: "Lovo",
    tagline: "AI voice generator and text-to-speech with 500+ realistic voices.",
    category: "Music",
    tags: ["tts", "voice", "narration", "podcast"],
    status: "live",
    url: "https://lovo.ai",
    pricing: "paid",
  },
  {
    id: "ultimate-vocal-remover",
    name: "UltimateVocalRemover",
    tagline: "Free, open-source AI tool for separating vocals from instrumentals.",
    category: "Music",
    tags: ["vocal-removal", "stems", "open-source", "audio"],
    status: "live",
    url: "https://ultimatevocalremover.com",
    pricing: "free",
  },
  {
    id: "lalal",
    name: "Lalal",
    tagline: "High-quality stem splitting to separate vocals, drums, bass, and more.",
    category: "Music",
    tags: ["stem-splitting", "vocal-removal", "mastering", "audio"],
    status: "live",
    url: "https://lalal.ai",
    pricing: "paid",
  },
  {
    id: "ai-coustics",
    name: "AI-Coustics",
    tagline: "AI audio enhancement that restores speech clarity from noisy recordings.",
    category: "Music",
    tags: ["audio-enhancement", "noise-reduction", "speech", "clarity"],
    status: "live",
    url: "https://ai-coustics.com",
    pricing: "free",
  },

  // ── Productivity ────────────────────────────────────────────────────────
  {
    id: "zapier",
    name: "Zapier",
    tagline: "Automate workflows between 6,000+ apps with AI-powered zaps.",
    category: "Productivity",
    tags: ["automation", "workflows", "integrations", "no-code"],
    status: "live",
    url: "https://zapier.com",
    pricing: "free",
  },
  {
    id: "axiom",
    name: "Axiom",
    tagline: "Automate browser tasks and web scraping without writing code.",
    category: "Productivity",
    tags: ["browser-automation", "scraping", "no-code", "bots"],
    status: "live",
    url: "https://axiom.ai",
    pricing: "paid",
    referralUrl: "https://axiom.ai/a?afmc=ua",
  },
  {
    id: "make",
    name: "Make",
    tagline: "Visual automation platform for complex multi-step workflows.",
    category: "Productivity",
    tags: ["automation", "visual", "workflows", "integrations"],
    status: "live",
    url: "https://make.com",
    pricing: "free",
    referralUrl: "https://www.make.com/en/register?pc=dan3dz",
  },
  {
    id: "rows-ai",
    name: "Rows AI",
    tagline: "Spreadsheets with built-in AI for data analysis and automation.",
    category: "Productivity",
    tags: ["spreadsheet", "data", "analysis", "automation"],
    status: "live",
    url: "https://rows.com",
    pricing: "free",
  },
  {
    id: "ydray",
    name: "Ydray",
    tagline: "Large file sharing and transfer with no size limits.",
    category: "Productivity",
    tags: ["file-sharing", "transfer", "storage", "large-files"],
    status: "live",
    url: "https://ydray.com",
    pricing: "free",
  },
  {
    id: "opus-pro",
    name: "Opus Pro",
    tagline: "Long Videos to Short Clips - YouTube to TikTok",
    category: "Productivity",
    tags: ["repurposing", "clips", "tiktok", "youtube"],
    status: "live",
    url: "https://opus.pro",
    pricing: "free trial",
  },
  {
    id: "repurpose",
    name: "Repurpose",
    tagline: "Automatically repurpose content across all your social media platforms.",
    category: "Productivity",
    tags: ["repurposing", "social-media", "automation", "content"],
    status: "live",
    url: "https://repurpose.io",
    pricing: "paid",
    referralUrl: "https://repurpose.io?fpr=3dzlabs",
  },
  {
    id: "syllaby",
    name: "Syllaby",
    tagline: "AI content strategy and video script generator for social media.",
    category: "Productivity",
    tags: ["content-strategy", "scripts", "social-media", "ai"],
    status: "live",
    url: "https://syllaby.io",
    pricing: "paid",
    referralUrl: "https://syllaby.io/?via=3dzlabs",
  },
  {
    id: "jotform",
    name: "Jotform",
    tagline: "AI-powered form builder for surveys, payments, and data collection.",
    category: "Productivity",
    tags: ["forms", "surveys", "payments", "automation"],
    status: "live",
    url: "https://jotform.com",
    pricing: "free",
  },
  {
    id: "like4like",
    name: "Like4Like",
    tagline: "Exchange social media likes and followers to grow your accounts.",
    category: "Productivity",
    tags: ["social-media", "growth", "followers", "engagement"],
    status: "live",
    url: "https://like4like.org",
    pricing: "free",
    referralUrl: "https://www.like4like.org/blog/free-youtube-likes.php?ref=3DZ",
    featured: true,
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    tagline: "AI copywriting tool for sales, marketing, and go-to-market content.",
    category: "Productivity",
    tags: ["copywriting", "marketing", "sales", "content"],
    status: "live",
    url: "https://copy.ai",
    pricing: "free",
  },
  {
    id: "postwise",
    name: "Postwise",
    tagline: "AI Twitter ghostwriter that grows your audience with viral posts.",
    category: "Productivity",
    tags: ["twitter", "ghostwriting", "social-media", "viral"],
    status: "live",
    url: "https://postwise.ai",
    pricing: "paid",
    referralUrl: "https://postwise.ai?_get=dan52",
    featured: true,
  },
  {
    id: "edrawsoft",
    name: "Edrawsoft",
    tagline: "AI-powered diagramming for flowcharts, org charts, and mind maps. Part of the Wondershare suite — flow chart, floor plan and diagram creator.",
    category: "Productivity",
    tags: ["diagrams", "flowcharts", "mind-maps", "org-charts", "wondershare"],
    status: "live",
    url: "https://edrawsoft.com",
    pricing: "free",
  },
  {
    id: "temp-mail",
    name: "Temp Mail",
    tagline: "Instant disposable email addresses for spam-free signups.",
    category: "Productivity",
    tags: ["email", "privacy", "disposable", "anonymous"],
    status: "live",
    url: "https://temp-mail.org",
    pricing: "free",
  },
  {
    id: "hitpaw",
    name: "HitPaw",
    tagline: "Online AI photo and video enhancement with one-click processing.",
    category: "Productivity",
    tags: ["photo", "video", "enhancement", "online"],
    status: "live",
    url: "https://online.hitpaw.com",
    pricing: "free",
  },
  {
    id: "resoomer",
    name: "Resoomer",
    tagline: "Free cognitive studio to process, study and summarize information.",
    category: "Productivity",
    tags: ["summarize", "study", "productivity", "text"],
    status: "live",
    url: "https://resoomer.com/en",
    pricing: "free",
  },
  {
    id: "topicfinder-productivity",
    name: "Topic Finder",
    tagline: "Search Relevant Topics",
    category: "Productivity",
    tags: ["topics", "content", "research", "seo"],
    status: "live",
    url: "https://topicfinder.com",
    pricing: "free limited",
  },
  {
    id: "lowfruits-productivity",
    name: "Lowfruits",
    tagline: "Keyword Search - Search Relevant Topics",
    category: "Productivity",
    tags: ["seo", "keywords", "low-competition", "research"],
    status: "live",
    url: "https://lowfruits.io",
    pricing: "paid",
  },
  {
    id: "clipbuddy-productivity",
    name: "Clipbuddy",
    tagline: "Long Videos to Shorts and Reels",
    category: "Productivity",
    tags: ["clips", "shorts", "reels", "repurposing"],
    status: "live",
    url: "https://clipbuddy.io",
    pricing: "paid",
  },

  // ── Research ────────────────────────────────────────────────────────────
  {
    id: "typeset",
    name: "SciSpace",
    tagline: "AI research assistant — chat with PDFs, literature reviews, and citations across 280M+ papers",
    category: "Research",
    tags: ["research", "papers", "summarization", "academic"],
    status: "live",
    url: "https://scispace.com",
    referralUrl: "https://scispace.com/?via=3dz",
    pricing: "free",
  },
  {
    id: "consensus",
    name: "Consensus",
    tagline: "Search and extract findings from 200M+ scientific papers.",
    category: "Research",
    tags: ["scientific", "papers", "search", "evidence"],
    status: "live",
    url: "https://consensus.app",
    pricing: "free",
  },
  {
    id: "wolfram-alpha",
    name: "Wolfram Alpha",
    tagline: "Computational knowledge engine for precise math and science answers.",
    category: "Research",
    tags: ["math", "science", "computation", "knowledge"],
    status: "live",
    url: "https://wolframalpha.com",
    pricing: "free",
  },
  {
    id: "wolframalpha",
    name: "Wolfram Alpha",
    tagline: "Expert level AI answers for complex math, science and research queries.",
    category: "Research",
    tags: ["math", "science", "research", "complex"],
    status: "live",
    url: "https://wolframalpha.com",
    pricing: "free limited",
  },
  {
    id: "socialblade",
    name: "SocialBlade",
    tagline: "Track and analyze social media growth stats across platforms.",
    category: "Research",
    tags: ["analytics", "social-media", "growth", "tracking"],
    status: "live",
    url: "https://socialblade.com",
    pricing: "free",
  },
  {
    id: "albus",
    name: "Albus",
    tagline: "AI ideas and content mapping tool — organize thoughts and research visually.",
    category: "Research",
    tags: ["content-mapping", "ideas", "research", "ai"],
    status: "live",
    url: "https://albus.org",
    pricing: "free",
  },
  {
    id: "upstract",
    name: "Upstract",
    tagline: "Curated tech and startup news aggregator powered by AI curation.",
    category: "Research",
    tags: ["news", "aggregator", "tech", "startup"],
    status: "live",
    url: "https://upstract.com",
    pricing: "paid",
  },
  {
    id: "thehiveindex",
    name: "The Hive Index",
    tagline: "Directory of online communities — find your people across any topic.",
    category: "Research",
    tags: ["communities", "directory", "research"],
    status: "live",
    url: "https://thehiveindex.com",
    pricing: "free",
  },
  {
    id: "leadinforce",
    name: "Leadinforce",
    tagline: "AI-powered B2B lead generation and sales intelligence platform.",
    category: "Research",
    tags: ["lead-gen", "b2b", "sales", "intelligence"],
    status: "live",
    url: "https://leadinforce.com",
    pricing: "paid",
  },
  {
    id: "topicfinder",
    name: "TopicFinder",
    tagline: "Discover high-traffic content topic ideas with AI-driven research.",
    category: "Research",
    tags: ["content", "topics", "seo", "research"],
    status: "live",
    url: "https://topicfinder.com",
    pricing: "free",
  },
  {
    id: "lowfruits",
    name: "LowFruits",
    tagline: "Find low-competition keywords that are easy to rank for quickly.",
    category: "Research",
    tags: ["seo", "keywords", "low-competition", "ranking"],
    status: "live",
    url: "https://lowfruits.io",
    pricing: "paid",
  },
  {
    id: "answersocrates",
    name: "AnswerSocrates",
    tagline: "Content Idea and Public Questions",
    category: "Research",
    tags: ["questions", "content-planning", "trending", "seo"],
    status: "live",
    url: "https://answersocrates.com",
    referralUrl: "https://answersocrates.com?via=3dz",
    pricing: "free",
  },
  {
    id: "answerthepublic",
    name: "AnswerThePublic",
    tagline: "Visualize search questions and trends to fuel your content strategy.",
    category: "Research",
    tags: ["search", "questions", "content-strategy", "seo"],
    status: "live",
    url: "https://answerthepublic.com",
    pricing: "$9/mo",
  },
  {
    id: "textguard",
    name: "TextGuard",
    tagline: "AI detector and paraphrase tools — identify and rewrite AI-generated content.",
    category: "Research",
    tags: ["ai-detector", "paraphrase", "writing", "research"],
    status: "live",
    url: "https://textguard.ai",
    pricing: "paid",
  },

  // ── Business ────────────────────────────────────────────────────────────
  {
    id: "logo-com",
    name: "Logo.com",
    tagline: "Generate professional logos and brand identity assets with AI.",
    category: "Business",
    tags: ["logo", "branding", "identity", "design"],
    status: "live",
    url: "https://logo.com",
    pricing: "free",
  },
  {
    id: "portfoliopilot",
    name: "PortfolioPilot",
    tagline: "AI-driven portfolio management and personalized investment insights.",
    category: "Business",
    tags: ["investing", "portfolio", "finance", "ai-advisor"],
    status: "live",
    url: "https://portfoliopilot.com",
    pricing: "free limited",
  },
  {
    id: "make-business",
    name: "Make",
    tagline: "Visual automation platform connecting apps and services for business.",
    category: "Business",
    tags: ["automation", "integration", "workflows", "no-code"],
    status: "live",
    url: "https://make.com",
    pricing: "free",
    referralUrl: "https://www.make.com/en/register?pc=dan3dz",
  },
  {
    id: "gofile",
    name: "Gofile",
    tagline: "Free unlimited file hosting and sharing with no registration required.",
    category: "Productivity",
    tags: ["file-sharing", "hosting", "upload", "free"],
    status: "live",
    url: "https://gofile.io",
    pricing: "free",
  },
  {
    id: "business-model-analyst",
    name: "BusinessModelAnalyst",
    tagline: "Deep dives into how the world's top companies make money.",
    category: "Business",
    tags: ["business-model", "analysis", "strategy", "research"],
    status: "live",
    url: "https://businessmodelanalyst.com",
    pricing: "free",
  },
  {
    id: "jasper",
    name: "Jasper",
    tagline: "Creates Content for Social Media - Company Co-Pilot",
    category: "Business",
    tags: ["marketing", "social-media", "copywriting", "content"],
    status: "live",
    url: "https://jasper.ai",
    pricing: "$40/mo",
    badgeLabel: "7-day trial",
  },
  {
    id: "gumroad",
    name: "Gumroad",
    tagline: "Sell and Create, Landing Pages, Online Courses, ANYTHING",
    category: "Business",
    tags: ["digital-products", "ecommerce", "courses", "landing-page"],
    status: "live",
    url: "https://gumroad.com",
    pricing: "free",
  },
  {
    id: "taja",
    name: "Taja",
    tagline: "Ai Algo, Expert SEO, Ai Optimizer, Schedule Content",
    category: "Business",
    tags: ["youtube", "seo", "optimization", "scheduling"],
    status: "live",
    url: "https://taja.ai",
    pricing: "free trial",
    badgeLabel: "7-day trial",
  },
  {
    id: "media-io",
    name: "Media.io",
    tagline: "All-in-one online media toolkit for video, audio, and image editing. Part of the Wondershare suite — video, audio and image AI tools.",
    category: "Video",
    tags: ["media", "video", "audio", "editing", "wondershare"],
    status: "live",
    url: "https://media.io",
    pricing: "free",
  },
  {
    id: "ideasai",
    name: "IdeasAI",
    tagline: "AI-generated startup ideas powered by GPT for endless inspiration.",
    category: "Business",
    tags: ["startup", "ideas", "inspiration", "gpt"],
    status: "live",
    url: "https://ideasai.com",
    pricing: "free",
  },

  // ── Web Design ──────────────────────────────────────────────────────────
  {
    id: "mixo",
    name: "Mixo",
    tagline: "Turn business ideas into websites and landing pages instantly with AI.",
    category: "Web Design",
    tags: ["website", "landing-page", "business", "ai"],
    status: "live",
    url: "https://mixo.io",
    pricing: "paid",
  },
  {
    id: "10web",
    name: "10Web",
    tagline: "AI-powered WordPress builder and optimizer with automated hosting.",
    category: "Web Design",
    tags: ["wordpress", "website-builder", "hosting", "ai"],
    status: "live",
    url: "https://10web.io",
    pricing: "paid",
  },
  {
    id: "jitter",
    name: "Jitter",
    tagline: "Animate UI components and design systems with browser-based motion.",
    category: "Web Design",
    tags: ["animation", "motion", "ui", "design-system"],
    status: "live",
    url: "https://jitter.video",
    pricing: "free",
  },
  {
    id: "figma",
    name: "Figma",
    tagline: "The industry-standard tool for collaborative UI design and prototyping.",
    category: "Web Design",
    tags: ["design", "prototyping", "ui", "collaboration"],
    status: "live",
    url: "https://figma.com",
    pricing: "free",
  },
  {
    id: "gamma",
    name: "Gamma",
    tagline: "Beautiful Ai Websites, Presentations, Docs",
    category: "Web Design",
    tags: ["websites", "presentations", "docs", "ai"],
    status: "live",
    url: "https://gamma.app",
    pricing: "free",
  },
  {
    id: "framer",
    name: "Framer",
    tagline: "Ai Website Creator",
    category: "Web Design",
    tags: ["website-builder", "ai", "design", "no-code"],
    status: "live",
    url: "https://framer.ai",
    pricing: "free",
  },

  // ── 3D & Animation ──────────────────────────────────────────────────────
  {
    id: "lumalabs",
    name: "LumaLabs",
    tagline: "AI NeRF 3D capture and video generation from photos and text.",
    category: "3D & Animation",
    tags: ["3d", "nerf", "video-gen", "capture"],
    status: "live",
    url: "https://lumalabs.ai",
    pricing: "free",
  },
  {
    id: "leiapix",
    name: "LeiaPix",
    tagline: "Convert 2D photos into stunning 3D depth animations instantly.",
    category: "3D & Animation",
    tags: ["3d", "depth", "animation", "photo-conversion"],
    status: "live",
    url: "https://immersity.ai",
    pricing: "free",
  },
  {
    id: "skybox",
    name: "Skybox",
    tagline: "Ai 3D World Creator",
    category: "3D & Animation",
    tags: ["360", "skybox", "panorama", "3d"],
    status: "live",
    url: "https://skybox.blockadelabs.com",
    pricing: "free",
  },
  {
    id: "daz3d",
    name: "Daz3D",
    tagline: "Ai 3D Model Creator - free models",
    category: "3D & Animation",
    tags: ["3d", "characters", "models", "rendering"],
    status: "draft",
    url: "https://daz3d.com",
    pricing: "free",
  },
  {
    id: "wonder-dynamics",
    name: "WonderDynamics",
    tagline: "AI VFX tool that automatically animates CG characters into live footage.",
    category: "3D & Animation",
    tags: ["vfx", "cg", "animation", "live-footage"],
    status: "live",
    url: "https://wonderdynamics.com",
    pricing: "paid",
  },
  {
    id: "sketch-meta",
    name: "Sketch Meta",
    tagline: "Animate hand-drawn sketches into moving 3D characters with AI.",
    category: "3D & Animation",
    tags: ["sketch", "animation", "3d", "ai"],
    status: "live",
    url: "https://sketch.metademolab.com",
    pricing: "free",
  },

  // ── Developers ──────────────────────────────────────────────────────────
  {
    id: "fal-ai",
    name: "Fal.ai",
    tagline: "Run image, video, 3D and audio AI models — built for developers.",
    category: "Developers",
    tags: ["developers", "api", "image", "video", "audio", "models"],
    status: "live",
    url: "https://fal.ai",
    pricing: "pay per use",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    tagline: "The AI community hub — open source models, datasets, and spaces.",
    category: "Developers",
    tags: ["developers", "open-source", "models", "datasets", "community"],
    status: "live",
    url: "https://huggingface.co",
    pricing: "free",
  },

  // ── Finance ─────────────────────────────────────────────────────────────
  {
    id: "portfoliopilot-finance",
    name: "PortfolioPilot",
    tagline: "AI investment advisor that tracks, analyzes, and optimizes your portfolio.",
    category: "Finance",
    tags: ["investing", "portfolio", "stocks", "ai-advisor"],
    status: "live",
    url: "https://portfoliopilot.com",
    pricing: "free limited",
  },
  {
    id: "hoopsai",
    name: "DealSize",
    tagline: "AI-powered stock and deal trading insights",
    category: "Finance",
    tags: ["trading", "stocks", "insights", "analysis"],
    status: "live",
    url: "https://dealsize.ai",
    pricing: "free",
  },

  // ── Learning ─────────────────────────────────────────────────────────────
  {
    id: "skillshare",
    name: "Skillshare",
    tagline: "Online learning platform with thousands of creative and business classes.",
    category: "Learning",
    tags: ["courses", "creative", "business", "online-learning"],
    status: "live",
    url: "https://skillshare.com",
    pricing: "free",
  },
  {
    id: "courseai",
    name: "Learning Studio AI",
    tagline: "Build and sell online courses with AI-generated content and structure.",
    category: "Learning",
    tags: ["course-creation", "ai", "elearning", "sell"],
    status: "live",
    url: "https://learningstudioai.com",
    pricing: "free",
  },
  {
    id: "classcentral",
    name: "Class Central",
    tagline: "Free online classes from top universities and big institutions worldwide.",
    category: "Learning",
    tags: ["courses", "learning", "university", "free"],
    status: "live",
    url: "https://classcentral.com",
    pricing: "free",
  },
  {
    id: "mindluster",
    name: "MindLuster",
    tagline: "Free online certified courses across hundreds of topics.",
    category: "Learning",
    tags: ["courses", "learning", "certified", "free"],
    status: "live",
    url: "https://mindluster.com",
    pricing: "free",
  },
  {
    id: "coursera",
    name: "Coursera",
    tagline: "Online courses, certificates and degrees from top universities and companies.",
    category: "Learning",
    tags: ["courses", "certificates", "learning", "university"],
    status: "live",
    url: "https://coursera.org",
    pricing: "free limited",
  },

  // ── Travel ──────────────────────────────────────────────────────────────
  {
    id: "skyscanner",
    name: "Skyscanner",
    tagline: "Search and compare cheap flights, hotels and car rentals worldwide.",
    category: "Travel",
    tags: ["travel", "flights", "hotels", "compare"],
    status: "live",
    url: "https://skyscanner.net",
    pricing: "free",
  },

  // ── Fun ─────────────────────────────────────────────────────────────────
  {
    id: "revive-ai",
    name: "Revive AI",
    tagline: "Animate and colorize old photos to bring memories back to life.",
    category: "Fun",
    tags: ["photo-animation", "colorize", "memories", "restore"],
    status: "live",
    url: "https://reviveai.com",
    pricing: "free",
  },
  {
    id: "interior-ai",
    name: "InteriorAI",
    tagline: "Redesign any room by uploading a photo and choosing an AI style.",
    category: "Fun",
    tags: ["interior-design", "room", "style", "ai"],
    status: "live",
    url: "https://interiorai.com",
    pricing: "free",
  },
  {
    id: "photoai",
    name: "PhotoAI",
    tagline: "Generate AI photos of yourself in any scene, style, or outfit.",
    category: "Fun",
    tags: ["ai-photos", "selfie", "avatar", "style"],
    status: "live",
    url: "https://photoai.com",
    pricing: "free",
  },
  {
    id: "faceswap",
    name: "FaceSwap",
    tagline: "Fun and instant AI face-swapping for photos and social content.",
    category: "Fun",
    tags: ["face-swap", "fun", "social", "photos"],
    status: "live",
    url: "https://artguru.ai",
    pricing: "free",
  },
  {
    id: "greenscreen-memes",
    name: "GreenScreenMemes",
    tagline: "Download ready-to-use green screen meme clips for your videos.",
    category: "Fun",
    tags: ["memes", "green-screen", "clips", "funny"],
    status: "live",
    url: "https://greenscreenmemes.com",
    pricing: "free",
  },
  {
    id: "replika",
    name: "Replika",
    tagline: "Your personal AI companion for conversation, support, and reflection.",
    category: "Fun",
    tags: ["companion", "chat", "mental-health", "ai"],
    status: "live",
    url: "https://replika.ai",
    pricing: "free",
  },
  {
    id: "rosebud-tokkingheads",
    name: "Tokkingheads",
    tagline: "Animate talking pictures — bring any photo to life with AI.",
    category: "Fun",
    tags: ["animate", "talking", "photos", "fun"],
    status: "live",
    url: "https://rosebud.ai/tokkingheads",
    pricing: "free limited",
  },
  {
    id: "artguru-fun",
    name: "Artguru",
    tagline: "Face Swap, Image Enhancer",
    category: "Fun",
    tags: ["face-swap", "enhancer", "ai", "fun"],
    status: "live",
    url: "https://artguru.ai",
    pricing: "free limited",
  },

  // ── Side Hustles (core) ──────────────────────────────────────────────────
  {
    id: "fiverr",
    name: "Fiverr",
    tagline: "Freelance Work",
    category: "Side Hustles",
    tags: ["freelance", "gigs", "services", "marketplace"],
    status: "live",
    url: "https://fiverr.com",
    pricing: "free",
  },
  {
    id: "upwork",
    name: "Upwork",
    tagline: "Freelance Work",
    category: "Side Hustles",
    tags: ["freelance", "remote", "projects", "tech"],
    status: "live",
    url: "https://upwork.com",
    pricing: "free",
  },
  {
    id: "textbroker",
    name: "Textbroker",
    tagline: "Paid to Write Content for Others - 3.2 Cents/Word",
    category: "Side Hustles",
    tags: ["writing", "content", "freelance", "paid"],
    status: "live",
    url: "https://textbroker.com",
    pricing: "free",
  },
  {
    id: "clickasnap",
    name: "Clickasnap",
    tagline: "Get Paid When Your Pics are Viewed - Pro $5/Month",
    category: "Side Hustles",
    tags: ["photography", "passive-income", "views", "photos"],
    status: "live",
    url: "https://clickasnap.com",
    pricing: "0.90 Cents/View",
  },
  {
    id: "envato",
    name: "Envato",
    tagline: "Sell Video, Audio, Design, Pics and 3D Models",
    category: "Side Hustles",
    tags: ["digital-assets", "templates", "themes", "marketplace"],
    status: "live",
    url: "https://author.envato.com",
    pricing: "free",
  },
  {
    id: "plrplanners",
    name: "PLR Planners",
    tagline: "Create Planners to Sell on Etsy",
    category: "Side Hustles",
    tags: ["plr", "planners", "resell", "digital-products"],
    status: "live",
    url: "https://plrplanners.com",
    pricing: "free",
  },
  {
    id: "clickworker",
    name: "Clickworker",
    tagline: "Image Tagging",
    category: "Side Hustles",
    tags: ["micro-jobs", "ai-training", "surveys", "gig"],
    status: "live",
    url: "https://clickworker.com",
    pricing: "free",
  },
  {
    id: "acx",
    name: "ACX",
    tagline: "Find Books to Read for Audio Books on Audible",
    category: "Side Hustles",
    tags: ["audiobooks", "amazon", "narration", "publishing"],
    status: "live",
    url: "https://acx.com",
    pricing: "Pay Negotiable",
  },
  {
    id: "grabjobs",
    name: "GrabJobs",
    tagline: "Ai Job Search - Remote Jobs",
    category: "Side Hustles",
    tags: ["jobs", "remote", "career", "ai-jobs"],
    status: "live",
    url: "https://grabjobs.co",
    pricing: "free",
  },

  // ── Print on Demand ──────────────────────────────────────────────────────
  {
    id: "printify",
    name: "Printify",
    tagline: "Create and sell custom print-on-demand products worldwide.",
    category: "Print on Demand",
    tags: ["print-on-demand", "sell", "custom", "products"],
    status: "live",
    url: "https://printify.com",
    pricing: "free limited",
  },
  {
    id: "etsy",
    name: "Etsy",
    tagline: "Create and sell custom products to millions of buyers worldwide.",
    category: "Print on Demand",
    tags: ["sell", "handmade", "custom", "marketplace"],
    status: "live",
    url: "https://etsy.com",
    pricing: "paid",
  },
  {
    id: "spreadshirt",
    name: "Spreadshirt",
    tagline: "Create and sell custom products online — t-shirts, hoodies and more.",
    category: "Print on Demand",
    tags: ["print-on-demand", "sell", "custom", "apparel"],
    status: "live",
    url: "https://spreadshirt.com",
    pricing: "free",
  },
  {
    id: "zazzle",
    name: "Zazzle",
    tagline: "Create and sell custom print-on-demand products across 1,000+ item types.",
    category: "Print on Demand",
    tags: ["print-on-demand", "custom", "products", "marketplace"],
    status: "live",
    url: "https://zazzle.com",
    pricing: "free",
  },

  // ── Phone Apps ───────────────────────────────────────────────────────────
  {
    id: "virbo",
    name: "Virbo",
    tagline: "Create AI avatar videos on your phone with multilingual voiceovers. Part of the Wondershare suite — professional film production tools.",
    category: "Phone Apps",
    tags: ["ai-avatar", "mobile", "video", "voiceover", "wondershare"],
    status: "live",
    url: "https://virbo.wondershare.com",
    pricing: "$20/mo",
  },
  {
    id: "ai-arta",
    name: "AI Arta",
    tagline: "Mobile AI art generator with 60+ unique artistic styles and filters.",
    category: "Phone Apps",
    tags: ["image-gen", "mobile", "art-styles", "filters"],
    status: "live",
    url: "https://ai-arta.com",
    pricing: "$7/wk",
  },
  {
    id: "usegenie",
    name: "UseGenie",
    tagline: "AI browser extension that summarizes pages and answers questions.",
    category: "Phone Apps",
    tags: ["browser", "summarize", "ai", "productivity"],
    status: "live",
    url: "https://usegenie.ai",
    pricing: "free",
  },
  {
    id: "glamapp",
    name: "GlamApp",
    tagline: "AI makeup try-on app that lets you test any beauty look virtually.",
    category: "Phone Apps",
    tags: ["beauty", "makeup", "try-on", "ar"],
    status: "live",
    url: "https://getglam.app",
    pricing: "$8/wk",
  },
  {
    id: "snaptik",
    name: "SnapTik",
    tagline: "Download TikTok videos without watermarks directly to your device.",
    category: "Phone Apps",
    tags: ["tiktok", "download", "no-watermark", "mobile"],
    status: "live",
    url: "https://snaptik.app",
    pricing: "free",
  },
  {
    id: "iplan",
    name: "iPlan",
    tagline: "AI-powered personal finance planner and budget tracker on mobile.",
    category: "Phone Apps",
    tags: ["finance", "budget", "planner", "mobile"],
    status: "live",
    url: "https://iplan.ai",
    pricing: "free",
  },

  // ── Side Hustles (additional) ────────────────────────────────────────────
  {
    id: "iplan-sh",
    name: "iPlan",
    tagline: "Virtual Travel Planner - Ai Created Itinerary",
    category: "Side Hustles",
    tags: ["travel", "itinerary", "ai", "planning"],
    status: "live",
    url: "https://iplan.ai",
    pricing: "free",
  },
  {
    id: "happyscribe",
    name: "Happy Scribe",
    tagline: "Transcribe Audio to Text, Subtitles, Translation",
    category: "Side Hustles",
    tags: ["transcription", "subtitles", "translation", "audio"],
    status: "live",
    url: "https://happyscribe.com",
    pricing: "free",
  },
  {
    id: "stitchfix",
    name: "Stitch Fix",
    tagline: "Virtual Personalized Stylist",
    category: "Side Hustles",
    tags: ["fashion", "stylist", "personal-shopping", "ai"],
    status: "live",
    url: "https://stitchfix.com",
    pricing: "$20",
  },
  {
    id: "importio",
    name: "Import.io",
    tagline: "Website Data Extraction",
    category: "Side Hustles",
    tags: ["web-scraping", "data", "extraction", "automation"],
    status: "live",
    url: "https://import.io",
    pricing: "$400/month",
  },
  {
    id: "wordcounter",
    name: "Word Counter",
    tagline: "Improve Word Choice and Writing Style",
    category: "Side Hustles",
    tags: ["writing", "word-count", "style", "tools"],
    status: "live",
    url: "https://wordcounter.net",
    pricing: "free",
  },
  {
    id: "answerthepublic-sh",
    name: "Answer The Public",
    tagline: "Public Search on AutoComplete Data - Google, YouTube, Bing",
    category: "Side Hustles",
    tags: ["search", "seo", "autocomplete", "research"],
    status: "live",
    url: "https://answerthepublic.com",
    pricing: "$9/month",
  },
  {
    id: "opensourcealternative",
    name: "Open Source Alternative",
    tagline: "Open Source Alternative Software - Google Drive Alt, NextCloud",
    category: "Side Hustles",
    tags: ["open-source", "alternatives", "software", "free"],
    status: "live",
    url: "https://opensourcealternative.to",
    pricing: "free",
  },
  {
    id: "kayak",
    name: "Kayak",
    tagline: "Compare Flights",
    category: "Side Hustles",
    tags: ["travel", "flights", "compare", "deals"],
    status: "live",
    url: "https://kayak.com",
    pricing: "free",
  },
  {
    id: "tripadvisor",
    name: "TripAdvisor",
    tagline: "Trip Helper - Itinerary",
    category: "Side Hustles",
    tags: ["travel", "reviews", "itinerary", "planning"],
    status: "live",
    url: "https://tripadvisor.com",
    pricing: "free",
  },
  {
    id: "booking",
    name: "Booking.com",
    tagline: "Trip Deals",
    category: "Side Hustles",
    tags: ["travel", "hotels", "deals", "booking"],
    status: "live",
    url: "https://booking.com",
    pricing: "free",
  },
  {
    id: "etsy-sh",
    name: "Etsy",
    tagline: "Sell Anything - Digital Planners, Tshirts, Etc.",
    category: "Side Hustles",
    tags: ["sell", "digital-products", "marketplace", "handmade"],
    status: "live",
    url: "https://etsy.com",
    pricing: "free",
  },
];

export const categories = [
  "Chat AI",
  "Creative",
  "Video",
  "Music",
  "Productivity",
  "Research",
  "Business",
  "Web Design",
  "3D & Animation",
  "Developers",
  "Finance",
  "Learning",
  "Travel",
  "Fun",
  "Print on Demand",
  "Phone Apps",
  "Side Hustles",
];
