export const tools = [
  // ── Chat AI ─────────────────────────────────────────────────────────────
  {
    id: "claude-ai",
    name: "Claude",
    tagline: "Anthropic's thoughtful AI assistant for reasoning, coding, and analysis.",
    category: "Chat AI",
    tags: ["chat", "llm", "coding", "writing"],
    status: "live",
    url: "https://claude.ai",
    pricing: "free",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "OpenAI's flagship conversational AI — the tool that started the era.",
    category: "Chat AI",
    tags: ["chat", "llm", "assistant", "gpt"],
    status: "live",
    url: "https://chat.openai.com",
    pricing: "free / $20",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    tagline: "AI-powered search engine with real-time answers and citations.",
    category: "Chat AI",
    tags: ["search", "research", "citations", "real-time"],
    status: "live",
    url: "https://perplexity.ai",
    pricing: "free",
  },
  {
    id: "monica",
    name: "Monica",
    tagline: "All-in-one AI assistant for browsing, writing, and translation.",
    category: "Chat AI",
    tags: ["assistant", "browser", "writing", "translation"],
    status: "live",
    url: "https://monica.im",
    pricing: "$10/mo",
  },
  {
    id: "droxy",
    name: "Droxy",
    tagline: "Build and deploy AI chatbots trained on your own content.",
    category: "Chat AI",
    tags: ["chatbot", "custom", "deployment", "no-code"],
    status: "live",
    url: "https://droxy.ai",
    pricing: "paid",
  },
  {
    id: "dante-ai",
    name: "Dante AI",
    tagline: "Create custom GPT chatbots from your documents and websites.",
    category: "Chat AI",
    tags: ["chatbot", "custom-gpt", "documents", "no-code"],
    status: "live",
    url: "https://dante-ai.com",
    pricing: "paid",
  },

  // ── Creative ────────────────────────────────────────────────────────────
  {
    id: "canva",
    name: "Canva",
    tagline: "AI-powered design platform for graphics, presentations, and more.",
    category: "Creative",
    tags: ["design", "graphics", "templates", "magic-ai"],
    status: "live",
    url: "https://canva.com",
    pricing: "free",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    tagline: "Premium text-to-image AI with cinematic, painterly output.",
    category: "Creative",
    tags: ["image-gen", "text-to-image", "art", "design"],
    status: "live",
    url: "https://midjourney.com",
    pricing: "$10/mo",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    tagline: "AI image generation with accurate text rendering inside images.",
    category: "Creative",
    tags: ["image-gen", "text-rendering", "logos", "typography"],
    status: "live",
    url: "https://ideogram.ai",
    pricing: "free",
  },
  {
    id: "playground-ai",
    name: "Playground AI",
    tagline: "Create and remix AI images with a generous free daily allowance.",
    category: "Creative",
    tags: ["image-gen", "remixing", "stable-diffusion", "free"],
    status: "live",
    url: "https://playgroundai.com",
    pricing: "free",
  },
  {
    id: "bing-create",
    name: "Bing Create",
    tagline: "Microsoft's free DALL-E powered image generator in the browser.",
    category: "Creative",
    tags: ["image-gen", "dall-e", "microsoft", "free"],
    status: "live",
    url: "https://bing.com/create",
    pricing: "free",
  },
  {
    id: "krea",
    name: "Krea",
    tagline: "Real-time AI image generation and enhancement with live canvas.",
    category: "Creative",
    tags: ["image-gen", "real-time", "upscaling", "canvas"],
    status: "live",
    url: "https://krea.ai",
    pricing: "free",
  },
  {
    id: "upscayl",
    name: "Upscayl",
    tagline: "Free and open-source AI image upscaler for desktop.",
    category: "Creative",
    tags: ["upscaling", "open-source", "desktop", "image"],
    status: "live",
    url: "https://upscayl.org",
    pricing: "free",
  },
  {
    id: "topaz-labs",
    name: "Topaz Labs",
    tagline: "Professional AI photo and video enhancement and noise reduction.",
    category: "Creative",
    tags: ["photo", "enhancement", "noise-reduction", "upscaling"],
    status: "live",
    url: "https://topazlabs.com",
    pricing: "paid",
  },
  {
    id: "replicate",
    name: "Replicate",
    tagline: "Run any open-source AI model via a clean API with pay-per-use pricing.",
    category: "Creative",
    tags: ["api", "open-source", "models", "stable-diffusion"],
    status: "live",
    url: "https://replicate.com",
    pricing: "free",
  },

  // ── Video ───────────────────────────────────────────────────────────────
  {
    id: "invideo-ai",
    name: "Invideo AI",
    tagline: "Turn a text prompt or script into a polished video in minutes.",
    category: "Video",
    tags: ["text-to-video", "marketing", "social", "voiceover"],
    status: "live",
    url: "https://invideo.io",
    pricing: "$20/mo",
  },
  {
    id: "kaiber",
    name: "Kaiber",
    tagline: "Transform audio, images, and prompts into cinematic AI video.",
    category: "Video",
    tags: ["ai-video", "animation", "music-video", "cinematic"],
    status: "live",
    url: "https://kaiber.ai",
    pricing: "paid",
  },
  {
    id: "visla",
    name: "Visla",
    tagline: "AI video creation platform for marketing and business content.",
    category: "Video",
    tags: ["video-creation", "marketing", "business", "stock"],
    status: "live",
    url: "https://visla.us",
    pricing: "free",
  },
  {
    id: "capcut",
    name: "CapCut",
    tagline: "Free AI-powered video editor with auto-captions and effects.",
    category: "Video",
    tags: ["video-editor", "captions", "effects", "mobile"],
    status: "live",
    url: "https://capcut.com",
    pricing: "free",
  },
  {
    id: "heygen",
    name: "HeyGen",
    tagline: "Create AI avatar videos with voice cloning and translation.",
    category: "Video",
    tags: ["ai-avatar", "voice-cloning", "translation", "presenter"],
    status: "live",
    url: "https://heygen.com",
    pricing: "paid",
  },
  {
    id: "d-id",
    name: "D-ID",
    tagline: "Animate still photos and generate talking AI presenters.",
    category: "Video",
    tags: ["talking-avatar", "photo-animation", "presenter", "digital-human"],
    status: "live",
    url: "https://d-id.com",
    pricing: "paid",
  },
  {
    id: "pika",
    name: "Pika",
    tagline: "Generate and edit video from text, images, or existing clips.",
    category: "Video",
    tags: ["text-to-video", "image-to-video", "editing", "generation"],
    status: "live",
    url: "https://pika.art",
    pricing: "free",
  },
  {
    id: "wisecut",
    name: "Wisecut",
    tagline: "Auto-edit long recordings with AI silence removal and B-roll.",
    category: "Video",
    tags: ["auto-edit", "silence-removal", "b-roll", "podcast"],
    status: "live",
    url: "https://wisecut.video",
    pricing: "free",
  },
  {
    id: "2short-ai",
    name: "2short.ai",
    tagline: "Repurpose long videos into viral short-form clips automatically.",
    category: "Video",
    tags: ["shorts", "repurposing", "clips", "social-media"],
    status: "live",
    url: "https://2short.ai",
    pricing: "paid",
  },

  // ── Music ───────────────────────────────────────────────────────────────
  {
    id: "suno-ai",
    name: "Suno AI",
    tagline: "Generate complete songs with vocals and instruments from a prompt.",
    category: "Music",
    tags: ["music-gen", "vocals", "songwriting", "audio"],
    status: "live",
    url: "https://suno.com",
    pricing: "free",
  },
  {
    id: "tracksy",
    name: "Tracksy",
    tagline: "AI music generation for background tracks and commercial use.",
    category: "Music",
    tags: ["background-music", "royalty-free", "commercial", "audio"],
    status: "live",
    url: "https://tracksy.ai",
    pricing: "free",
  },
  {
    id: "musicgen",
    name: "MusicGen",
    tagline: "Meta's open-source music generation model, free on HuggingFace.",
    category: "Music",
    tags: ["open-source", "music-gen", "meta", "huggingface"],
    status: "live",
    url: "https://huggingface.co/facebook/musicgen-large",
    pricing: "free",
  },

  // ── Productivity ────────────────────────────────────────────────────────
  {
    id: "zapier",
    name: "Zapier",
    tagline: "Automate workflows between 6,000+ apps with AI-powered zaps.",
    category: "Productivity",
    tags: ["automation", "workflows", "integrations", "no-code"],
    status: "live",
    url: "https://zapier.com",
    pricing: "free",
  },
  {
    id: "axiom",
    name: "Axiom",
    tagline: "Automate browser tasks and web scraping without writing code.",
    category: "Productivity",
    tags: ["browser-automation", "scraping", "no-code", "bots"],
    status: "live",
    url: "https://axiom.ai",
    pricing: "paid",
  },
  {
    id: "make",
    name: "Make",
    tagline: "Visual automation platform for complex multi-step workflows.",
    category: "Productivity",
    tags: ["automation", "visual", "workflows", "integrations"],
    status: "live",
    url: "https://make.com",
    pricing: "free",
  },
  {
    id: "rows-ai",
    name: "Rows AI",
    tagline: "Spreadsheets with built-in AI for data analysis and automation.",
    category: "Productivity",
    tags: ["spreadsheet", "data", "analysis", "automation"],
    status: "live",
    url: "https://rows.com",
    pricing: "free",
  },
  {
    id: "ydray",
    name: "Ydray",
    tagline: "Large file sharing and transfer with no size limits.",
    category: "Productivity",
    tags: ["file-sharing", "transfer", "storage", "large-files"],
    status: "live",
    url: "https://ydray.com",
    pricing: "free",
  },

  // ── Research ────────────────────────────────────────────────────────────
  {
    id: "typeset",
    name: "Typeset",
    tagline: "AI research assistant for discovering and summarizing papers.",
    category: "Research",
    tags: ["research", "papers", "summarization", "academic"],
    status: "live",
    url: "https://typeset.io",
    pricing: "free",
  },
  {
    id: "consensus",
    name: "Consensus",
    tagline: "Search and extract findings from 200M+ scientific papers.",
    category: "Research",
    tags: ["scientific", "papers", "search", "evidence"],
    status: "live",
    url: "https://consensus.app",
    pricing: "free",
  },
  {
    id: "wolfram-alpha",
    name: "Wolfram Alpha",
    tagline: "Computational knowledge engine for precise math and science answers.",
    category: "Research",
    tags: ["math", "science", "computation", "knowledge"],
    status: "live",
    url: "https://wolframalpha.com",
    pricing: "free",
  },
  {
    id: "socialblade",
    name: "SocialBlade",
    tagline: "Track and analyze social media growth stats across platforms.",
    category: "Research",
    tags: ["analytics", "social-media", "growth", "tracking"],
    status: "live",
    url: "https://socialblade.com",
    pricing: "free",
  },

  // ── Business ────────────────────────────────────────────────────────────
  {
    id: "logo-com",
    name: "Logo.com",
    tagline: "Generate professional logos and brand identity assets with AI.",
    category: "Business",
    tags: ["logo", "branding", "identity", "design"],
    status: "live",
    url: "https://logo.com",
    pricing: "free",
  },
  {
    id: "portfoliopilot",
    name: "PortfolioPilot",
    tagline: "AI-driven portfolio management and personalized investment insights.",
    category: "Business",
    tags: ["investing", "portfolio", "finance", "ai-advisor"],
    status: "live",
    url: "https://portfoliopilot.com",
    pricing: "free",
  },
  {
    id: "tiny-acquisitions",
    name: "Tiny Acquisitions",
    tagline: "Marketplace for buying and selling small digital products under $5K.",
    category: "Business",
    tags: ["marketplace", "acquisitions", "digital-products", "micro-saas"],
    status: "live",
    url: "https://tinyacquisitions.com",
    pricing: "free",
  },

  // ── Web Design ──────────────────────────────────────────────────────────
  {
    id: "hocoos",
    name: "Hocoos",
    tagline: "AI website builder that creates a full site from a short description.",
    category: "Web Design",
    tags: ["website-builder", "ai", "no-code", "landing-page"],
    status: "live",
    url: "https://hocoos.com",
    pricing: "free",
  },
  {
    id: "mixo",
    name: "Mixo",
    tagline: "Launch an MVP landing page from a single sentence in seconds.",
    category: "Web Design",
    tags: ["landing-page", "mvp", "startup", "launch"],
    status: "live",
    url: "https://mixo.io",
    pricing: "paid",
  },
  {
    id: "10web",
    name: "10Web",
    tagline: "AI-powered WordPress builder and optimizer with automated hosting.",
    category: "Web Design",
    tags: ["wordpress", "website-builder", "hosting", "ai"],
    status: "live",
    url: "https://10web.io",
    pricing: "paid",
  },
  {
    id: "jitter",
    name: "Jitter",
    tagline: "Animate UI components and design systems with browser-based motion.",
    category: "Web Design",
    tags: ["animation", "motion", "ui", "design-system"],
    status: "live",
    url: "https://jitter.video",
    pricing: "free",
  },
  {
    id: "figma",
    name: "Figma",
    tagline: "The industry-standard tool for collaborative UI design and prototyping.",
    category: "Web Design",
    tags: ["design", "prototyping", "ui", "collaboration"],
    status: "live",
    url: "https://figma.com",
    pricing: "free",
  },
];

export const categories = [
  "Chat AI",
  "Creative",
  "Video",
  "Music",
  "Productivity",
  "Research",
  "Business",
  "Web Design",
];
